### ISSUE TITLE
needs to run in background

### ISSUE THREAD

**Issue by aspiers** [cute-jumper/gmpl-mode#1]
Thanks for this mode - it's awesome! :-)

I started working with some more difficult problems which take a very long time to find the optimal solution, and I noticed that with these, emacs totally hangs when you hit `C-c C-c` to solve.  AFAICS it's invoking `glpsol` in the foreground?  If it was run as a subprocess then you could carry on using emacs whilst it writes partial output to the buffer.

**Comment by cute-jumper** [comment]
Yeah, currently it runs the command synchronously. Using `start-process` instead of `shell-command-to-string` should make it non-blocking. I can fix this when I get some time. Thanks!

**Comment by cute-jumper** [comment]
@aspiers If you're still interested, I've just pushed a patch to make `C-c C-c` run asynchronously. Let me know if there is any problem. Thanks!

**Comment by aspiers** [comment]
Cool, thanks a lot! :-)
